# Generated by Django 3.2.5 on 2022-03-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineMobileStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='upload/%Y/%m/%d/')),
                ('p_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TopSale',
        ),
    ]
