# Generated by Django 3.2.5 on 2022-03-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineMobileStore', '0002_auto_20220306_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
