# Generated by Django 3.2.5 on 2022-03-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineMobileStore', '0004_newphone_specialprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialprice',
            name='image',
        ),
    ]
