# Generated by Django 3.2.5 on 2022-04-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineMobileStore', '0008_auto_20220404_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(max_length=200)),
                ('displayType', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=200)),
                ('wlan', models.CharField(max_length=200)),
                ('usb', models.CharField(max_length=200)),
                ('cameraPrimary', models.CharField(max_length=200)),
                ('cameraVideo', models.CharField(max_length=200)),
                ('cameraSecondary', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('chipset', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineMobileStore.product')),
            ],
        ),
    ]
