# Generated by Django 3.2.5 on 2022-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineMobileStore', '0016_auto_20220420_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
